-- =============================================================================
-- 5. customer_shopping_behavior_analysis.sql
-- Input : table `cleaned_customer_shopping_behavior`, loaded from
--         "4. cleaned_customer_shopping_behavior.csv" (see
--         "3. customer_shopping_behavior.ipynb")
-- Output: answers to the 10 business questions below
-- =============================================================================

-- DROP 2 columns such as age_group_2 and age_group_3 using ALTER TABLE table_name DROP COLUMN column_name, so the new csv file won't have them like original file.
-- Check data
SELECT * FROM cleaned_customer_shopping_behavior LIMIT 5;

-- Q1, What is the total revenue generated by male and female customers?
SELECT gender, SUM(purchase_amount) as total_revenue
FROM cleaned_customer_shopping_behavior
GROUP BY gender;

-- Q2: Which customers used a discount but still spent more than the avg purchase amount?
SELECT 
    customer_id, 
    purchase_amount
FROM cleaned_customer_shopping_behavior
WHERE discount_applied = 'Yes' 
  AND purchase_amount >= (
      SELECT AVG(purchase_amount) 
      FROM cleaned_customer_shopping_behavior
  );
  
  -- Q3: Which are the top 5 products with the highest avg review ratings?
  SELECT item_purchased, ROUND(avg(review_rating),2) as 'Average Product Ratings' from cleaned_customer_shopping_behavior 
  group by item_purchased
  order by avg(review_rating) DESC
  limit 5;
  
  -- Q4: Compare the avg purchase amouts between standard and express shipping
  select shipping_type, ROUND(avg(purchase_amount),2) as 'Average Purchases Amount' from cleaned_customer_shopping_behavior
  where shipping_type in ('Express' , 'Standard')
  group by shipping_type;
  
  -- Q5: Do subscribed customers spend more? Compare avg spend and total revenue between subscribers and non-subscriber
  select subscription_status, count(customer_id) as 'Total Customers', round(avg(purchase_amount),2) as 'Average Spend' ,  SUM(purchase_amount) AS 'Total Revenue'
  from cleaned_customer_shopping_behavior
  group by subscription_status;

-- Q6: Which 5 products have the highest percentage of purchases with discount applied?
SELECT 
    item_purchased,
    ROUND(SUM(CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END) * 100 / COUNT(*),
            2) AS discount_rate
FROM
    cleaned_customer_shopping_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7: Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment
SELECT 
    (CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END) AS customers_group,
    COUNT(*) AS number_of_customers
FROM
    cleaned_customer_shopping_behavior
GROUP BY customers_group;

-- Q8:  What are the top 3 most purchased products with each category
with item_count as (select  
    category,
    item_purchased,
    count(customer_id) as total_orders,
    row_number() OVER (partition by category order by count(customer_id) DESC) as item_rank
FROM
    cleaned_customer_shopping_behavior
GROUP BY category, item_purchased)
    
SELECT 
    item_rank, category, item_purchased, total_orders
FROM
    item_count
WHERE
    item_rank <= 3
ORDER BY category;

-- Q9: Are customers who are repeat buyers (more than 5 previous puchases) also likely to subscribe? 
select subscription_status, count(customer_id) as repeat_buyers
from cleaned_customer_shopping_behavior
where previous_purchases > 5
group by subscription_status;

-- Q10: What is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as total_revenue
from cleaned_customer_shopping_behavior
group by age_group
order by total_revenue DESC